- name: create ansible group 
  group: name=apache state=absent
  tags:
    - apache

- name: create apache user
  user: name=apache group=apache 
  tags: 
    - apache
  # ensure apache is installed in redhat and centos platform distribution
- name: ensure apache is at the latest version
  yum: name=httpd state=present
  when: ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat'
  tags:
    - apache
  
  # ensure apache is installed in redhat and centos platform distribution
- name: Install apache
  apt: 
    name: "{{ item }}" 
    state: latest
  with_items:
    - apache2
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'
  tags:
    - apache

  # restart apache in ubuntu or debian
- name: restart apache
  service: 
    name: apache2 
    state: started 
    enabled: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - apache

  # replacing default index.html
- name: replace default index.html file
  template: src=../templates/index.html.j2 dest=/var/www/html/index.html mode=0644 owner=apache group=root
  notify:
    - restart apache
  tags:
    - apache
- name: ensure apache is running 
  service: name=httpd state=started enabled=yes
  tags:
    - apache

  # enabling 80 port in firewall
- name: Open port 80
  firewalld: service=http permanent=true state=enabled
  tags:
    - apache
  
  # restart firewall in redhat or centos
- name: start the firewalld service
  service: name=firewalld state=restarted
  tags:
    - firewall
